apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ch1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/jr-do/docker-k8s-security-ch1
    chart: ch1
    targetRevision: ">=0.1.0"
    helm:
      parameters:
        - name: backend.imagePullSecrets[0]
          value: ghcr-pull
        - name: frontend.imagePullSecrets[0]
          value: ghcr-pull
  destination:
    server: https://kubernetes.default.svc
    namespace: app-ch1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
