apiVersion: v2
name: ch1
description: Umbrella chart for backend and frontend
type: application
version: 0.1.1
appVersion: "1.0.0"

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"
  - name: frontend
    version: 0.1.0
    repository: "file://charts/frontend"
