backend:
  image:
    repository: ghcr.io/jr-do/docker-k8s-security-ch1-backend
    tag: latest
    pullPolicy: Always
  imagePullSecrets: []
  service:
    port: 8080
  env:
    PORT: "8080"

frontend:
  image:
    repository: ghcr.io/jr-do/docker-k8s-security-ch1-frontend
    tag: latest
    pullPolicy: Always
  imagePullSecrets: []
  service:
    port: 80
    type: NodePort
    nodePort: 30080
  env:
    API_BASE_URL: ""
  backendService:
    name: ch1-backend
    port: 8080
