image:
  repository: ghcr.io/jr-do/docker-k8s-security-ch1-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

env:
  API_BASE_URL: ""

backendService:
  name: ch1-backend
  port: 8080

resources: {}
